# Generated by Django 5.2.16 on 2026-07-26 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(choices=[('two_cards', '2 cartes (2fr 1fr)'), ('three_cards', '3 cartes (1fr 1fr 1fr)'), ('full_width', 'Pleine largeur (1fr)'), ('two_rows', '2 rangées (1fr 1fr)'), ('one_big', 'Grande + petite (3fr 1fr)')], max_length=20, unique=True)),
                ('grid_style', models.CharField(help_text="ex: '2fr 1fr'", max_length=50)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('tag', models.CharField(blank=True, default='', max_length=100)),
                ('subtitle', models.CharField(blank=True, default='', max_length=255)),
                ('cta_label', models.CharField(blank=True, default='', max_length=50)),
                ('link', models.URLField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='banners/')),
                ('tint_from', models.CharField(default='6B35FF', max_length=6)),
                ('tint_to', models.CharField(default='FF4580', max_length=6)),
                ('zone', models.CharField(choices=[('hero_slider', 'Hero Slider'), ('side_card', 'Side Card')], default='hero_slider', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['zone', 'position'],
                'unique_together': {('zone', 'position')},
            },
        ),
    ]
