# Generated by Django 5.2.16 on 2026-07-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='image_url_ext',
            field=models.URLField(blank=True, default=''),
        ),
    ]
