# Generated by Django 5.2.16 on 2026-07-26 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_bannerimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannerimage',
            options={'ordering': ['position']},
        ),
        migrations.RemoveField(
            model_name='bannerimage',
            name='sort_order',
        ),
        migrations.RemoveField(
            model_name='bannerimage',
            name='url',
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/gallery/'),
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='image_url_ext',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='bannerimage',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banner',
            name='tint_from',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='banner',
            name='tint_to',
            field=models.CharField(blank=True, default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='bannerimage',
            name='banner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='banners.banner'),
        ),
    ]
