# Generated by Django 5.2.16 on 2026-07-28 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_alter_bannerimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='zone',
            field=models.CharField(choices=[('hero_bg', 'Fond du Hero'), ('hero_slider', 'Hero Slider'), ('side_card', 'Side Card')], default='hero_slider', max_length=20),
        ),
    ]
