# Generated by Django 5.2.16 on 2026-07-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_alter_banner_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='zone',
            field=models.CharField(choices=[('hero_bg', 'Fond du Hero'), ('bottom_slider', 'Slider du bas'), ('hero_slider', 'Hero Slider'), ('side_card', 'Side Card')], default='hero_slider', max_length=20),
        ),
    ]
