# Generated by Django 5.2.16 on 2026-08-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0006_alter_banner_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cta_label_ar',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='cta_label_en',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='cta_label_fr',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_ar',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_en',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='subtitle_fr',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='tag_ar',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='tag_en',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='tag_fr',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
