# Generated by Django 5.2.16 on 2026-08-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarrierProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('mock', 'Transporteur (démo)'), ('first_delivery', 'First Delivery')], max_length=40, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.URLField(blank=True)),
                ('base_url', models.URLField(blank=True)),
                ('credentials', models.JSONField(blank=True, default=dict)),
                ('webhook_secret', models.CharField(blank=True, max_length=255)),
                ('cod_supported', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('sort_order', 'name'),
            },
        ),
    ]
