# Generated by Django 5.2.15 on 2026-06-04 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierstore',
            name='founded_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='response_time_hrs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
