# Generated by Django 5.2.16 on 2026-07-20 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierprofile',
            name='doc_cin',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='doc_logo',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='doc_rib',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplierprofile',
            name='doc_rne',
            field=models.TextField(blank=True, default=''),
        ),
    ]
