# Generated by Django 5.2.16 on 2026-08-04 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_bannedphone_user_phone_verified_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierstore',
            name='about_image_url',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='about_images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='about_title_accent',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='about_title_main',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='hero_title',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='highlight_image_1',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='highlight_image_2',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='mission',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='stats_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='stats_title',
            field=models.TextField(blank=True, default=''),
        ),
    ]
