# Generated by Django 5.2.16 on 2026-08-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_supplierstore_about_image_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierstore',
            name='about_title_accent_ar',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='about_title_accent_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='about_title_accent_fr',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='about_title_main_ar',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='about_title_main_en',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='about_title_main_fr',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='hero_title_ar',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='hero_title_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='hero_title_fr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='mission_ar',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='mission_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='mission_fr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='stats_description_ar',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='stats_description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='stats_description_fr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='stats_title_ar',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='stats_title_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='supplierstore',
            name='stats_title_fr',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
