# Generated by Django 5.2.16 on 2026-08-17 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_document',
            field=models.FileField(blank=True, null=True, upload_to='business_docs/'),
        ),
        migrations.AddField(
            model_name='user',
            name='business_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='business_patente',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='business_rejection_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_rne',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='business_status',
            field=models.CharField(choices=[('none', 'Non soumis'), ('pending', 'En attente'), ('verified', 'Vérifié'), ('rejected', 'Rejeté')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='business_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_verifications', to=settings.AUTH_USER_MODEL),
        ),
    ]
