# Generated by Django 5.2.16 on 2026-07-14 19:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0003_alter_cartitem_options'),
        ('products', '0007_reviewphoto'),
        ('users', '0003_user_last_seen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderRegion',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='region_info', serialize=False, to='orders.order')),
                ('gouvernorat', models.CharField(choices=[('tunis', 'Tunis'), ('ariana', 'Ariana'), ('ben_arous', 'Ben Arous'), ('manouba', 'La Manouba'), ('nabeul', 'Nabeul'), ('zaghouan', 'Zaghouan'), ('bizerte', 'Bizerte'), ('beja', 'Béja'), ('jendouba', 'Jendouba'), ('kef', 'Le Kef'), ('siliana', 'Siliana'), ('kairouan', 'Kairouan'), ('kasserine', 'Kassérine'), ('sidi_bouzid', 'Sidi Bouzid'), ('sousse', 'Sousse'), ('monastir', 'Monastir'), ('mahdia', 'Mahdia'), ('sfax', 'Sfax'), ('gafsa', 'Gafsa'), ('tozeur', 'Tozeur'), ('kebili', 'Kébili'), ('gabes', 'Gabès'), ('medenine', 'Médenine'), ('tataouine', 'Tataouine')], db_index=True, max_length=30)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('confidence', models.FloatField(default=1.0)),
                ('parsed_from', models.TextField(blank=True, help_text='Adresse brute parsée')),
            ],
            options={
                'db_table': 'analytics_order_region',
                'indexes': [models.Index(fields=['gouvernorat'], name='analytics_o_gouvern_bad818_idx')],
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('channel', models.CharField(db_index=True, default='unknown', max_length=30)),
                ('device_type', models.CharField(default='desktop', max_length=20)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('page_view_count', models.PositiveIntegerField(default=1)),
                ('converted', models.BooleanField(db_index=True, default=False)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_sessions', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_session',
            },
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_type', models.CharField(choices=[('supplier_shop', 'Boutique fournisseur'), ('product_detail', 'Détail produit'), ('catalogue', 'Catalogue'), ('home', 'Accueil'), ('search', 'Recherche')], default='product_detail', max_length=30)),
                ('session_key', models.CharField(db_index=True, max_length=64)),
                ('channel', models.CharField(choices=[('direct', 'Direct'), ('search', 'Recherche organique'), ('social', 'Réseaux sociaux'), ('email', 'Email'), ('referral', 'Référence externe'), ('app_ios', 'App iOS'), ('app_android', 'App Android'), ('unknown', 'Inconnu')], db_index=True, default='unknown', max_length=30)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('referrer', models.URLField(blank=True, max_length=500)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], default='desktop', max_length=20)),
                ('user_agent', models.TextField(blank=True)),
                ('viewed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to='products.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='page_views', to='users.supplierprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_views', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pageviews', to='analytics.session')),
            ],
            options={
                'db_table': 'analytics_pageview',
            },
        ),
        migrations.CreateModel(
            name='OrderChannel',
            fields=[
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='channel_info', serialize=False, to='orders.order')),
                ('channel', models.CharField(choices=[('direct', 'Direct'), ('search', 'Recherche organique'), ('social', 'Réseaux sociaux'), ('email', 'Email'), ('referral', 'Référence externe'), ('app_ios', 'App iOS'), ('app_android', 'App Android'), ('unknown', 'Inconnu')], db_index=True, default='unknown', max_length=30)),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=100)),
                ('device_type', models.CharField(default='desktop', max_length=20)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='analytics.session')),
            ],
            options={
                'db_table': 'analytics_order_channel',
            },
        ),
        migrations.CreateModel(
            name='MonthlyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(db_index=True)),
                ('month', models.PositiveSmallIntegerField(db_index=True)),
                ('revenue_target', models.DecimalField(decimal_places=3, help_text='Objectif de CA en TND', max_digits=12)),
                ('orders_target', models.PositiveIntegerField(default=0)),
                ('new_buyers_target', models.PositiveIntegerField(default=0)),
                ('views_target', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_targets', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_targets', to='users.supplierprofile')),
            ],
            options={
                'db_table': 'analytics_monthly_target',
                'ordering': ['-year', '-month'],
                'indexes': [models.Index(fields=['supplier', 'year', 'month'], name='analytics_m_supplie_b225f9_idx')],
                'unique_together': {('supplier', 'year', 'month')},
            },
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['channel', 'started_at'], name='analytics_s_channel_4bdf89_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['converted', 'started_at'], name='analytics_s_convert_2e75b8_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['supplier', 'viewed_at'], name='analytics_p_supplie_9de1d0_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['product', 'viewed_at'], name='analytics_p_product_fa2380_idx'),
        ),
        migrations.AddIndex(
            model_name='pageview',
            index=models.Index(fields=['channel', 'viewed_at'], name='analytics_p_channel_c18be4_idx'),
        ),
    ]
