# Generated by Django 5.2.16 on 2026-08-01 02:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('products', '0010_category_banner_link_category_banner_url'),
        ('users', '0005_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pageview',
            name='client_view_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pageview',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ProductEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('event_type', models.CharField(choices=[('view_description', 'Ouverture description'), ('view_image', 'Vue image / galerie'), ('select_variant', 'Sélection variante'), ('add_to_cart', 'Ajout au panier'), ('contact_supplier', 'Contact fournisseur')], db_index=True, max_length=30)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='products.product')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_events', to='users.supplierprofile')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'analytics_product_event',
                'indexes': [models.Index(fields=['product', 'created_at'], name='analytics_p_product_f33a83_idx'), models.Index(fields=['product', 'event_type'], name='analytics_p_product_94aa16_idx'), models.Index(fields=['supplier', 'created_at'], name='analytics_p_supplie_d52fa5_idx')],
            },
        ),
    ]
