# Generated by Django 5.2.15 on 2026-06-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content_raw',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_filtered',
        ),
    ]
