# Generated by Django 5.2.16 on 2026-08-01 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_remove_message_content_raw_and_more'),
        ('products', '0010_category_banner_link_category_banner_url'),
        ('users', '0005_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['buyer', 'last_msg_at'], name='conversatio_buyer_i_df1340_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['supplier', 'last_msg_at'], name='conversatio_supplie_ed9c35_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='messages_convers_3ebb41_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'is_read'], name='messages_convers_78b517_idx'),
        ),
    ]
