# Generated by Django 5.2.16 on 2026-08-20 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_conversation_conversatio_buyer_i_df1340_idx_and_more'),
        ('orders', '0008_customizationrequest_remove_cartitem_uniq_cart_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='customization_request',
            field=models.ForeignKey(blank=True, help_text='Uniquement pour les messages liés à un devis de personnalisation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='orders.customizationrequest'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Texte'), ('quote_request', 'Demande de devis'), ('quote_response', 'Réponse de devis'), ('quote_accepted', 'Devis accepté'), ('quote_rejected', 'Devis refusé')], default='text', max_length=20),
        ),
    ]
