# Generated by Django 5.2.15 on 2026-06-04 22:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0002_supplierstore_founded_year_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('call_confirmed', 'Confirmée par appel'), ('in_production', 'En production'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=30)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Non payée'), ('paid', 'Payée'), ('refunded', 'Remboursée')], default='unpaid', max_length=20)),
                ('payment_method', models.CharField(blank=True, choices=[('cod', 'Paiement à la livraison'), ('d17', 'D17'), ('flouci', 'Flouci'), ('sobflous', 'Sobflous'), ('virement', 'Virement bancaire')], max_length=20)),
                ('total_tnd', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('discount_tnd', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('shipping_address', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SubOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('in_production', 'En production'), ('shipped', 'Expédiée'), ('delivered', 'Livrée'), ('cancelled', 'Annulée')], default='pending', max_length=30)),
                ('subtotal_tnd', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('delivery_type', models.CharField(choices=[('groshop', 'Livraison GROSHOP'), ('supplier', 'Livraison fournisseur'), ('third_party', 'Transporteur tiers')], default='groshop', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_orders', to='orders.order')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_orders', to='users.supplierprofile')),
            ],
            options={
                'db_table': 'sub_orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price_tnd', models.DecimalField(decimal_places=3, max_digits=10)),
                ('total_tnd', models.DecimalField(decimal_places=3, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.product')),
                ('sub_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.suborder')),
            ],
            options={
                'db_table': 'order_items',
            },
        ),
    ]
