# Generated by Django 5.2.15 on 2026-06-27 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-created_at']},
        ),
    ]
