# Generated by Django 5.2.16 on 2026-08-15 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_reference'),
        ('products', '0015_product_specs_raw_ar_product_specs_raw_en_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='guest_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('buyer__isnull', False), ('guest_id__isnull', True)), models.Q(('buyer__isnull', True), ('guest_id__isnull', False)), _connector='OR'), name='cart_owner_xor'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('buyer__isnull', False)), fields=('buyer', 'product', 'variant'), name='uniq_cart_user'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_id__isnull', False)), fields=('guest_id', 'product', 'variant'), name='uniq_cart_guest'),
        ),
    ]
