# Generated by Django 5.2.16 on 2026-08-20 16:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_conversation_conversatio_buyer_i_df1340_idx_and_more'),
        ('orders', '0007_alter_cartitem_unique_together_cartitem_guest_id_and_more'),
        ('products', '0017_product_allow_customization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomizationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('values', models.JSONField(blank=True, default=list, help_text='Valeurs saisies : [{field_id, label, field_type, value}]')),
                ('status', models.CharField(choices=[('pending', 'En attente de devis'), ('quoted', 'Devis envoyé'), ('accepted', 'Accepté'), ('rejected', 'Refusé'), ('expired', 'Expiré')], default='pending', max_length=20)),
                ('quoted_price_tnd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('quoted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('supplier_note', models.TextField(blank=True, default='', help_text='Message optionnel du fournisseur avec le devis')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customization_requests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='uniq_cart_user',
        ),
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='uniq_cart_guest',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='customization_values',
            field=models.JSONField(blank=True, default=list, help_text="Valeurs saisies par l'acheteur : [{field_id, label, field_type, value}]"),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_customized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customization_values',
            field=models.JSONField(blank=True, default=list, help_text='Snapshot des valeurs saisies : [{field_id, label, field_type, value}]'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_customized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customizationrequest',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customizationrequest',
            name='conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customization_requests', to='messaging.conversation'),
        ),
        migrations.AddField(
            model_name='customizationrequest',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_requests', to='products.product'),
        ),
        migrations.AddField(
            model_name='customizationrequest',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='products.productvariant'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='customization_request',
            field=models.ForeignKey(blank=True, help_text="Rempli uniquement pour les items issus d'un devis accepté (mode quote).", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_items', to='orders.customizationrequest'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='customization_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='orders.customizationrequest'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('buyer__isnull', False), ('is_customized', False)), fields=('buyer', 'product', 'variant'), name='uniq_cart_user'),
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(condition=models.Q(('guest_id__isnull', False), ('is_customized', False)), fields=('guest_id', 'product', 'variant'), name='uniq_cart_guest'),
        ),
        migrations.AddIndex(
            model_name='customizationrequest',
            index=models.Index(fields=['buyer', 'status'], name='customizati_buyer_i_946f28_idx'),
        ),
        migrations.AddIndex(
            model_name='customizationrequest',
            index=models.Index(fields=['product', 'status'], name='customizati_product_f9ffb8_idx'),
        ),
        migrations.AddIndex(
            model_name='customizationrequest',
            index=models.Index(fields=['conversation'], name='customizati_convers_aad8cf_idx'),
        ),
    ]
