# Generated by Django 5.2.15 on 2026-06-11 02:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SpinPrize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=150)),
                ('prize_type', models.CharField(choices=[('coupon', 'Coupon réduction'), ('free_shipping', 'Livraison gratuite'), ('no_prize', 'Pas de chance')], max_length=20)),
                ('value_tnd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('probability', models.DecimalField(decimal_places=4, max_digits=5)),
                ('color_hex', models.CharField(blank=True, max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'spin_prizes',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('amount_tnd', models.DecimalField(decimal_places=3, max_digits=10)),
                ('source', models.CharField(choices=[('spin_wheel', 'Roue de la fortune'), ('promo', 'Promotion admin'), ('admin', 'Créé par admin')], default='admin', max_length=20)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'coupons',
            },
        ),
        migrations.CreateModel(
            name='UserSpin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_ref', models.CharField(max_length=200, unique=True)),
                ('spun_at', models.DateTimeField(auto_now_add=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spin', to='gamification.coupon')),
                ('prize', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spins', to='gamification.spinprize')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_spins',
            },
        ),
    ]
