# Generated by Django 5.2.15 on 2026-06-04 22:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('new_order', 'Nouvelle commande'), ('order_status', 'Statut commande mis à jour'), ('message', 'Nouveau message'), ('promo', 'Promotion'), ('product_approved', 'Produit approuvé'), ('product_rejected', 'Produit rejeté'), ('new_review', 'Nouvel avis'), ('spin_reward', 'Récompense roue')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('channel', models.CharField(choices=[('push', 'Notification push'), ('in_app', 'In-app'), ('email', 'Email')], default='in_app', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx')],
            },
        ),
    ]
