# Generated by Django 5.2.16 on 2026-08-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_devicetoken_pushnotification_delete_notification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pushnotification',
            name='body_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='body_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='title_ar',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pushnotification',
            name='title_fr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
