# Generated by Django 5.2.15 on 2026-06-04 21:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0002_supplierstore_founded_year_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('icon_name', models.CharField(blank=True, max_length=100)),
                ('image_url', models.TextField(blank=True)),
                ('is_hot', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='products.category')),
            ],
            options={
                'db_table': 'categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=300)),
                ('slug', models.SlugField(max_length=350, unique=True)),
                ('description', models.TextField(blank=True)),
                ('sku', models.CharField(blank=True, max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50)),
                ('moq', models.IntegerField()),
                ('base_price_tnd', models.DecimalField(decimal_places=3, max_digits=10)),
                ('video_url', models.TextField(blank=True)),
                ('stock_qty', models.IntegerField(default=0)),
                ('sold_count', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('rating_avg', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('rating_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('pending_review', 'En attente de validation'), ('approved', 'Approuvé'), ('rejected', 'Rejeté')], default='draft', max_length=20)),
                ('badge_choice', models.BooleanField(default=False)),
                ('badge_flash', models.BooleanField(default=False)),
                ('badge_flash_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.supplierprofile')),
            ],
            options={
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'db_table': 'product_images',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ProductPriceTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_qty', models.IntegerField()),
                ('max_qty', models.IntegerField(blank=True, null=True)),
                ('price_tnd', models.DecimalField(decimal_places=3, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='products.product')),
            ],
            options={
                'db_table': 'product_price_tiers',
                'ordering': ['min_qty'],
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['supplier'], name='products_supplie_1396c7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_categor_4083ff_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['status'], name='products_status_a30e64_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sold_count'], name='products_sold_co_e478bd_idx'),
        ),
    ]
