# Generated by Django 5.2.15 on 2026-06-20 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_brand_product_pack_size_product_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specs_raw',
            field=models.TextField(blank=True, default=''),
        ),
    ]
