# Generated by Django 5.2.15 on 2026-06-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_specs_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='delivery_days',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_price_tnd',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
