# Generated by Django 5.2.15 on 2026-06-20 22:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_product_delivery_days_product_shipping_price_tnd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.TextField()),
                ('sort_order', models.IntegerField(default=0)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='products.review')),
            ],
            options={
                'db_table': 'review_photos',
                'ordering': ['sort_order'],
            },
        ),
    ]
