# Generated by Django 5.2.16 on 2026-07-21 19:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductChoiceGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('sort_order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_groups', to='products.product')),
            ],
            options={
                'db_table': 'product_choice_groups',
                'ordering': ['sort_order'],
            },
        ),
        migrations.AddField(
            model_name='productvariant',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.productchoicegroup'),
        ),
    ]
