# Generated by Django 5.2.16 on 2026-07-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_productchoicegroup_productvariant_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='banner_link',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='category',
            name='banner_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
