# Generated by Django 5.2.16 on 2026-08-03 22:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_category_banner_link_category_banner_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='in_stock',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_block_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_block_size',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_mode',
            field=models.CharField(choices=[('free', 'Gratuite'), ('flat', 'Fixe'), ('tiered', 'Par tranche de quantité'), ('per_block', 'Par palier')], default='flat', max_length=12),
        ),
        migrations.AddField(
            model_name='productpricetier',
            name='old_price_tnd',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='ProductShippingTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_qty', models.IntegerField()),
                ('price_tnd', models.DecimalField(decimal_places=3, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_tiers', to='products.product')),
            ],
            options={
                'db_table': 'product_shipping_tiers',
                'ordering': ['min_qty'],
            },
        ),
    ]
