# Generated by Django 5.2.16 on 2026-08-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_product_in_stock_product_shipping_block_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_poster_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
