# Generated by Django 5.2.16 on 2026-08-04 02:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_product_video_poster_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariantCombo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('combo_key', models.CharField(db_index=True, max_length=300)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_combos', to='products.product')),
                ('variants', models.ManyToManyField(related_name='combos', to='products.productvariant')),
            ],
            options={
                'db_table': 'product_variant_combos',
            },
        ),
        migrations.CreateModel(
            name='ProductComboPriceTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('min_qty', models.IntegerField()),
                ('max_qty', models.IntegerField(blank=True, null=True)),
                ('price_tnd', models.DecimalField(decimal_places=3, max_digits=10)),
                ('old_price_tnd', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tiers', to='products.productvariantcombo')),
            ],
            options={
                'db_table': 'product_combo_price_tiers',
                'ordering': ['min_qty'],
            },
        ),
    ]
