# Generated by Django 5.2.16 on 2026-08-13 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_category_name_ar_category_name_en_category_name_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specs_raw_ar',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specs_raw_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='specs_raw_fr',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
