# Generated by Django 5.2.16 on 2026-08-17 15:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_specs_raw_ar_product_specs_raw_en_and_more'),
        ('users', '0010_user_business_document_user_business_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_visibility',
            field=models.CharField(choices=[('public', 'Public'), ('verified_only', 'Boutiques vérifiées uniquement')], default='public', help_text='Si "verified_only", le prix est masqué aux users non-vérifiés.', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductPriceUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='null = permanent', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_unlocks', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'product_price_unlocks',
                'indexes': [models.Index(fields=['user', 'product'], name='product_pri_user_id_b79ba5_idx'), models.Index(fields=['expires_at'], name='product_pri_expires_f38d89_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'user'), name='uniq_product_price_unlock')],
            },
        ),
        migrations.CreateModel(
            name='SupplierUserUnlock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='null = permanent', null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_unlocks', to='users.supplierprofile')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplier_unlocks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'supplier_user_unlocks',
                'indexes': [models.Index(fields=['user', 'supplier'], name='supplier_us_user_id_5c2ea9_idx'), models.Index(fields=['expires_at'], name='supplier_us_expires_cdac82_idx')],
                'constraints': [models.UniqueConstraint(fields=('supplier', 'user'), name='uniq_supplier_user_unlock')],
            },
        ),
    ]
