# Generated by Django 5.2.16 on 2026-08-20 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_product_price_visibility_productpriceunlock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allow_customization',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_extra_price_tnd',
            field=models.DecimalField(decimal_places=3, default=0, help_text="Mode 'fixed' uniquement : surcoût par unité (0 = inclus dans le prix).", max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_instructions',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_mode',
            field=models.CharField(choices=[('fixed', 'Prix fixe'), ('quote', 'Sur devis')], default='fixed', help_text="'fixed' = surcoût pré-fixé ; 'quote' = fournisseur cote après avoir vu la demande.", max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='customization_required',
            field=models.BooleanField(default=False, help_text="Mode 'fixed' uniquement : la perso est-elle obligatoire pour commander ?"),
        ),
        migrations.CreateModel(
            name='ProductCustomizationField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=200)),
                ('field_type', models.CharField(choices=[('text', 'Texte court'), ('image', 'Image'), ('file', 'Fichier'), ('number', 'Nombre'), ('color', 'Couleur')], max_length=10)),
                ('required', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('constraints', models.JSONField(blank=True, default=dict, help_text='Contraintes optionnelles : {max_chars, max_file_mb, accepted_formats: []}')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customization_fields', to='products.product')),
            ],
            options={
                'db_table': 'product_customization_fields',
                'ordering': ['sort_order'],
            },
        ),
    ]
